import { sqliteTable, text, integer, primaryKey } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";
import type { WebAuthnCredential } from "#auth-utils"

/**
 * Drizzle ORM Schema Definition
 * 
 * This file defines the structure of the SQLite database.
 * It handles Users, Security Logs (Login Attempts), and WebAuthn Credentials (Passkeys).
 */

// --------------------------------------------------------------------------
// 1. Users Table
// --------------------------------------------------------------------------
// The core identity table. 
// Note: 'password' is nullable because users might register purely via 
// WebAuthn (Passkeys) without ever setting a traditional password.
export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name'),
  email: text('email').notNull().unique(),
  login: text('login'), // Optional username or handle
  password: text('password') // Nullable: Support for Passwordless users
});

// --------------------------------------------------------------------------
// 2. Login Attempts Table
// --------------------------------------------------------------------------
// Used for Rate Limiting and Brute Force protection.
// We track IP, time, and success status to block repeated failed attempts.
export const loginAttempts = sqliteTable('login_attempts', {
  // Added autoIncrement
  id: integer('id').primaryKey({ autoIncrement: true }), 
  
  // Link to user. onDelete: 'cascade' ensures that if we delete a user, 
  // their logs are cleaned up automatically.
  userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }),
  
  ip: text('ip').notNull(),
  timestamp: integer('timestamp').notNull(), // Unix timestamp
  
  // 'boolean' mode is cleaner for success/fail
  // Stored as 0 or 1 in SQLite, but treated as JS Boolean in the app.
  success: integer('success', { mode: 'boolean' }).notNull()
});

// --------------------------------------------------------------------------
// 3. Credentials Table (WebAuthn / Passkeys)
// --------------------------------------------------------------------------
// This table stores the public keys and metadata for user devices.
// It essentially replaces the 'password' check for modern logins.
export const credentials = sqliteTable("credentials", {
    userId: integer("user_id")
      .references(() => users.id, { onDelete: 'cascade' })
      .notNull(),
    
    // FIX 1: Credential IDs are long strings (Base64), NOT integers
    // This ID comes from the browser/authenticator and is unique to the key pair.
    id: text("id").notNull().unique(), 

    // The Public Key used to verify the signature generated by the user's device.
    publicKey: text("public_key").notNull(),

    // Counter prevents "Replay Attacks". The authenticator increments this 
    // every time it's used. If we receive a counter lower/equal to what we have, it's a clone/hack.
    counter: integer("counter").notNull(),

    // Whether the credential is synced (e.g., iCloud Keychain, Google Password Manager)
    backedUp: integer("backed_up", { mode: "boolean" }).notNull(),
  
    // Stores how the key communicates (USB, NFC, BLE, Internal).
    // Drizzle handles the JSON stringify/parse automatically via mode: "json".
    transports: text("transports", { mode: "json" }).notNull()
      .$type<WebAuthnCredential["transports"]>()
  },
  (table) => [
    // FIX 2: Correct primaryKey syntax
    // We use a Composite Primary Key. A credential is uniquely identified 
    // by the User it belongs to AND its Credential ID.
    primaryKey({ columns: [table.userId, table.id] }) 
  ]
);

// --------------------------------------------------------------------------
// 4. Relations (Application Level)
// --------------------------------------------------------------------------
// This allows the "Magic" queries in Drizzle (e.g., db.query.credentials.findFirst({ with: { user: true } }))
// It defines the graph connections between tables for the ORM.

// FIX 3: Correct relations syntax
export const credentialsRelations = relations(credentials, ({ one }) => ({
  user: one(users, {
    fields: [credentials.userId],
    references: [users.id]
  })
}));
